name: Flutter CI/CD

on:
  push:
    branches:
      - main # Это проверка только на релизе. Под разработку можете менять так как принято в команде

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable # Или укажите конкретную версию

      - name: Get pub dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Build IPA
        run: flutter build ios --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/*.apk
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: build/ios/archive/*.ipa


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-release
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ios-release

      - name: Upload to Firebase App Distribution (Android) #Optional
        uses: wzieba/firebase-app-distribution-action@v1
        with:
          app: ${{ secrets.YOUR_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          release_notes: "New release from CI/CD"
          apk: build/app/outputs/flutter-apk/*.apk

      - name: Upload to Firebase App Distribution (iOS) #Optional
        uses: wzieba/firebase-app-distribution-action@v1
        with:
          app: ${{ secrets.YOUR_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          release_notes: "New release from CI/CD"
          ipa: build/ios/archive/*.ipa



