name: Python CI/CD

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_PASSWORD: ${{ vars.DB_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Setup virtual env
        run: python3 -m venv .venv
      - name: Activate virtual env
        run: source .venv/bin/activate
      - name: Install deps
        run: pip install -r requirements/test.txt
      - name: Ruff check
        run: ruff check
      - name: Test project
        run: pytest --cov=src .
      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/python-app:latest . # Заменить на свой

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/python-app:latest # Заменить на свой
